### PR TITLE
Don't store full path to AR and RANLIB

### PR DESCRIPTION
**Pull request by isuruf**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by peterjc** [comment]
@Zimmi48 are happy being named as a co-maintainer of this recipe?

**Comment by peterjc** [comment]
Ah, I see you have agreed here: https://github.com/conda-forge/ocaml-feedstock/pull/22#issuecomment-751383219

**Comment by peterjc** [comment]
@conda-forge-admin, please rerender

**Review by peterjc — APPROVED** [review]

**Comment by Zimmi48** [comment]
@peterjc Until you merge this PR, you're still the only maintainer, so the only one who can merge this.

**Comment by peterjc** [comment]
At the time I approved it, the post re-render tests were still running. Anyway, glad to see it merged now - thank you!

**Pull request merged**
