### PR TITLE
OSXArm migration

### PR DESCRIPTION
**Pull request by jjerphan**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

Continuation of #35.

### CODE REVIEW

**Comment by jjerphan** [comment]
@mottelet: you can able to push on that branch if you accept the invitation to join my fork as a collaborator.

**Comment by jjerphan** [comment]
I unfortunately don't have bandwidth to continue this PR for now; the easiest would be to have someone from @conda-forge/ocaml help with the setup, I believe.

**Comment by peterjc** [comment]
Thanks for your efforts - sadly I don't think we have the OCaml expertise to help either. I only got involved myself as the user of a tool built with OCaml.

**Comment by Zimmi48** [comment]
As far as I'm concerned, I lack both the OCaml internals expertise (only got involved because this was a dependency of Coq) and the Conda expertise (never really used conda). I've been unable to help lately by lack of time, so I'm going to leave this organization and the teams I'm in.

**Comment by jjerphan** [comment]
I am closing this issue for now, I might reopen in the future if I get access to a `osx_arm64` machine.

**Pull request closed without merging**
